import test from "node:test";
import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import { mkdtemp, mkdir } from "node:fs/promises";
import { pathExists, writeJsonFile, writeUtf8 } from "../src/utils/fs.ts";
import { PlanningJournalStore } from "../src/planning/journal.ts";
import { getRepoStatePaths } from "../src/utils/paths.ts";
import { ProjectStateStore } from "../src/state/store.ts";
import { WatcherManager } from "../src/watchers/manager.ts";
import { createLogger, waitFor } from "./helpers/harness.ts";

function createPlanningOpenSpec(changeDir: string, proposalPath: string) {
  return {
    status: async (cwd: string, changeName: string) => ({
      command: `openspec status --change ${changeName} --json`,
      cwd,
      stdout: "{}",
      stderr: "",
      durationMs: 1,
      parsed: {
        changeName,
        schemaName: "spec-driven",
        isComplete: await pathExists(proposalPath),
        applyRequires: ["proposal"],
        artifacts: [
          {
            id: "proposal",
            outputPath: proposalPath,
            status: await pathExists(proposalPath) ? "done" : "ready",
          },
        ],
      },
    }),
    instructionsArtifact: async (cwd: string, artifactId: string, changeName: string) => ({
      command: `openspec instructions ${artifactId} --change ${changeName} --json`,
      cwd,
      stdout: "{}",
      stderr: "",
      durationMs: 1,
      parsed: {
        changeName,
        artifactId,
        schemaName: "spec-driven",
        changeDir,
        outputPath: proposalPath,
        description: "proposal",
        instruction: "Write the proposal artifact.",
        template: "# Proposal\n",
        dependencies: [],
        unlocks: ["apply"],
      },
    }),
    instructionsApply: async (cwd: string, changeName: string) => ({
      command: `openspec instructions apply --change ${changeName} --json`,
      cwd,
      stdout: "{}",
      stderr: "",
      durationMs: 1,
      parsed: {
        changeName,
        changeDir,
        schemaName: "spec-driven",
        contextFiles: { proposal: proposalPath },
        progress: { total: 1, complete: 0, remaining: 1 },
        tasks: [{ id: "1.1", description: "Build demo", done: false }],
        state: await pathExists(proposalPath) ? "ready" : "blocked",
        instruction: "Implement the remaining task.",
      },
    }),
  } as any;
}

test("watcher planning flow completes", async () => {
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), "clawspec-watcher-plan-"));
  const workspacePath = path.join(tempRoot, "workspace");
  const repoPath = path.join(workspacePath, "demo-app");
  const changeName = "watch-plan";
  const changeDir = path.join(repoPath, "openspec", "changes", changeName);
  const proposalPath = path.join(changeDir, "proposal.md");
  await mkdir(changeDir, { recursive: true });
  await writeUtf8(path.join(changeDir, ".openspec.yaml"), "schema: spec-driven\n");

  const stateStore = new ProjectStateStore(tempRoot, "archives");
  await stateStore.initialize();
  const notifierMessages: string[] = [];

  const fakeAcpClient = {
    runTurn: async () => {
      await writeUtf8(proposalPath, "# Proposal\n\nGenerated by watcher.\n");
      await writeJsonFile(getRepoStatePaths(repoPath, "archives").executionResultFile, {
        version: 1,
        changeName,
        mode: "apply",
        status: "running",
        timestamp: new Date().toISOString(),
        summary: "Updated proposal.",
        progressMade: true,
        currentArtifact: "proposal",
        changedFiles: ["openspec/changes/watch-plan/proposal.md"],
        notes: ["Proposal refreshed"],
        taskCounts: { total: 1, complete: 0, remaining: 1 },
      });
    },
    cancelSession: async () => undefined,
    closeSession: async () => undefined,
  };

  const manager = new WatcherManager({
    stateStore,
    openSpec: createPlanningOpenSpec(changeDir, proposalPath),
    archiveDirName: "archives",
    logger: createLogger(),
    notifier: { send: async (_: string, text: string) => { notifierMessages.push(text); } } as any,
    acpClient: fakeAcpClient as any,
    pollIntervalMs: 25,
  });

  const channelKey = "discord:watch-plan:default:main";
  await stateStore.createProject(channelKey);
  await stateStore.updateProject(channelKey, (current) => ({
    ...current,
    workspacePath,
    repoPath,
    projectName: "demo-app",
    projectTitle: "Demo App",
    changeName,
    changeDir,
    status: "planning",
    phase: "planning_sync",
    planningJournal: {
      dirty: true,
      entryCount: 1,
      lastEntryAt: new Date(Date.now() - 60_000).toISOString(),
    },
    execution: {
      mode: "apply",
      action: "plan",
      state: "armed",
      armedAt: new Date().toISOString(),
    },
  }));

  await manager.start();
  await manager.wake(channelKey);
  await waitFor(async () => (await stateStore.getActiveProject(channelKey))?.status === "ready");
  await manager.stop();

  const project = await stateStore.getActiveProject(channelKey);
  assert.equal(project?.status, "ready");
  assert.equal(project?.phase, "tasks");
  assert.equal(project?.planningJournal?.dirty, false);
  assert.equal(await pathExists(proposalPath), true);
  assert.equal(notifierMessages.some((m) => m.includes("Planning") && m.includes("proposal")), true);
  assert.equal(notifierMessages.some((m) => m.includes("Planning ready") && m.includes("Next: run `cs-work` to start implementation")), true);
});

test("planning fallback normalizes artifact path", async () => {
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), "clawspec-watcher-plan-fallback-"));
  const workspacePath = path.join(tempRoot, "workspace");
  const repoPath = path.join(workspacePath, "demo-app");
  const changeName = "watch-plan-fallback";
  const changeDir = path.join(repoPath, "openspec", "changes", changeName);
  const proposalPath = path.join(changeDir, "proposal.md");
  await mkdir(changeDir, { recursive: true });

  const stateStore = new ProjectStateStore(tempRoot, "archives");
  await stateStore.initialize();

  // Use relative outputPath to test normalization
  const fakeOpenSpec = {
    status: async (cwd: string, cn: string) => ({
      command: `openspec status --change ${cn} --json`,
      cwd, stdout: "{}", stderr: "", durationMs: 1,
      parsed: {
        changeName: cn,
        schemaName: "spec-driven",
        isComplete: await pathExists(proposalPath),
        applyRequires: ["proposal"],
        artifacts: [{ id: "proposal", outputPath: "proposal.md", status: await pathExists(proposalPath) ? "done" : "ready" }],
      },
    }),
    instructionsArtifact: async (cwd: string, artifactId: string, cn: string) => ({
      command: `openspec instructions ${artifactId} --change ${cn} --json`,
      cwd, stdout: "{}", stderr: "", durationMs: 1,
      parsed: {
        changeName: cn, artifactId, schemaName: "spec-driven", changeDir,
        outputPath: "proposal.md",
        description: "proposal", instruction: "Write the proposal artifact.",
        template: "# Proposal\n", dependencies: [], unlocks: ["apply"],
      },
    }),
    instructionsApply: async (cwd: string, cn: string) => ({
      command: `openspec instructions apply --change ${cn} --json`,
      cwd, stdout: "{}", stderr: "", durationMs: 1,
      parsed: {
        changeName: cn, changeDir, schemaName: "spec-driven",
        contextFiles: { proposal: proposalPath },
        progress: { total: 1, complete: 0, remaining: 1 },
        tasks: [{ id: "1.1", description: "Build demo", done: false }],
        state: await pathExists(proposalPath) ? "ready" : "blocked",
        instruction: "Implement the remaining task.",
      },
    }),
  } as any;

  const manager = new WatcherManager({
    stateStore,
    openSpec: fakeOpenSpec,
    archiveDirName: "archives",
    logger: createLogger(),
    notifier: { send: async () => undefined } as any,
    acpClient: {
      runTurn: async () => { await writeUtf8(proposalPath, "# Proposal\n"); },
      cancelSession: async () => undefined,
      closeSession: async () => undefined,
    } as any,
    pollIntervalMs: 25,
  });

  const channelKey = "discord:watch-plan-fallback:default:main";
  await stateStore.createProject(channelKey);
  await stateStore.updateProject(channelKey, (current) => ({
    ...current,
    workspacePath, repoPath, projectName: "demo-app", projectTitle: "Demo App",
    changeName, changeDir, status: "planning", phase: "planning_sync",
    planningJournal: { dirty: true, entryCount: 1, lastEntryAt: new Date(Date.now() - 60_000).toISOString() },
    execution: { mode: "apply", action: "plan", state: "armed", armedAt: new Date().toISOString() },
  }));

  await manager.start();
  await manager.wake(channelKey);
  await waitFor(async () => (await stateStore.getActiveProject(channelKey))?.status === "ready");
  await manager.stop();

  const project = await stateStore.getActiveProject(channelKey);
  assert.deepEqual(project?.lastExecution?.changedFiles, ["openspec/changes/watch-plan-fallback/proposal.md"]);
});

test("watcher force-refreshes planning artifacts when journal is dirty and OpenSpec reports all artifacts done", async () => {
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), "clawspec-watcher-plan-forced-"));
  const workspacePath = path.join(tempRoot, "workspace");
  const repoPath = path.join(workspacePath, "demo-app");
  const changeName = "watch-plan-forced";
  const changeDir = path.join(repoPath, "openspec", "changes", changeName);
  const proposalPath = path.join(changeDir, "proposal.md");
  const designPath = path.join(changeDir, "design.md");
  const specPath = path.join(changeDir, "specs", "city-info-api", "spec.md");
  const tasksPath = path.join(changeDir, "tasks.md");
  await mkdir(path.dirname(specPath), { recursive: true });
  await writeUtf8(path.join(changeDir, ".openspec.yaml"), "schema: spec-driven\n");
  await writeUtf8(proposalPath, "# Proposal\n\nOld proposal.\n");
  await writeUtf8(designPath, "# Design\n\nOld design.\n");
  await writeUtf8(specPath, "# Spec\n\nOld spec.\n");
  await writeUtf8(tasksPath, "- [x] 1.1 Old task\n");

  const stateStore = new ProjectStateStore(tempRoot, "archives");
  await stateStore.initialize();
  const notifierMessages: string[] = [];
  const runOrder: string[] = [];

  const outputPaths: Record<string, string> = {
    proposal: proposalPath,
    specs: specPath,
    design: designPath,
    tasks: tasksPath,
  };

  const fakeOpenSpec = {
    status: async (cwd: string, cn: string) => ({
      command: `openspec status --change ${cn} --json`,
      cwd, stdout: "{}", stderr: "", durationMs: 1,
      parsed: {
        changeName: cn,
        schemaName: "spec-driven",
        isComplete: true,
        applyRequires: ["tasks"],
        artifacts: [
          { id: "proposal", outputPath: proposalPath, status: "done" },
          { id: "specs", outputPath: specPath, status: "done" },
          { id: "design", outputPath: designPath, status: "done" },
          { id: "tasks", outputPath: tasksPath, status: "done" },
        ],
      },
    }),
    instructionsArtifact: async (cwd: string, artifactId: string, cn: string) => ({
      command: `openspec instructions ${artifactId} --change ${cn} --json`,
      cwd, stdout: "{}", stderr: "", durationMs: 1,
      parsed: {
        changeName: cn,
        artifactId,
        schemaName: "spec-driven",
        changeDir,
        outputPath: outputPaths[artifactId]!,
        description: artifactId,
        instruction: `Write ${artifactId}.`,
        template: `# ${artifactId}\n`,
        dependencies: [],
        unlocks: ["apply"],
      },
    }),
    instructionsApply: async (cwd: string, cn: string) => ({
      command: `openspec instructions apply --change ${cn} --json`,
      cwd, stdout: "{}", stderr: "", durationMs: 1,
      parsed: {
        changeName: cn,
        changeDir,
        schemaName: "spec-driven",
        contextFiles: {
          proposal: proposalPath,
          specs: specPath,
          design: designPath,
          tasks: tasksPath,
        },
        progress: { total: 1, complete: 0, remaining: 1 },
        tasks: [{ id: "1.1", description: "Implement refreshed task", done: false }],
        state: "ready",
        instruction: "Implement the refreshed task.",
      },
    }),
  } as any;

  const fakeAcpClient = {
    runTurn: async ({ text }: { text: string }) => {
      const match = text.match(/Artifact:\s+([a-z-]+)/i);
      const artifactId = match?.[1];
      if (!artifactId || !outputPaths[artifactId]) {
        throw new Error(`Missing artifact id in prompt: ${text}`);
      }
      runOrder.push(artifactId);
      if (artifactId === "tasks") {
        await writeUtf8(tasksPath, "- [ ] 1.1 Implement refreshed task\n");
      } else {
        await writeUtf8(outputPaths[artifactId], `# ${artifactId}\n\nRefreshed ${artifactId}.\n`);
      }
      await writeJsonFile(getRepoStatePaths(repoPath, "archives").executionResultFile, {
        version: 1,
        changeName,
        mode: "apply",
        status: "running",
        timestamp: new Date().toISOString(),
        summary: `Updated ${artifactId}.`,
        progressMade: true,
        currentArtifact: artifactId,
        changedFiles: [`openspec/changes/${changeName}/${path.relative(changeDir, outputPaths[artifactId]!).replace(/\\/g, "/")}`],
        notes: [`Refreshed ${artifactId}`],
        taskCounts: { total: 1, complete: 0, remaining: 1 },
      });
    },
    cancelSession: async () => undefined,
    closeSession: async () => undefined,
  };

  const manager = new WatcherManager({
    stateStore,
    openSpec: fakeOpenSpec,
    archiveDirName: "archives",
    logger: createLogger(),
    notifier: { send: async (_: string, text: string) => { notifierMessages.push(text); } } as any,
    acpClient: fakeAcpClient as any,
    pollIntervalMs: 25,
  });

  const channelKey = "discord:watch-plan-forced:default:main";
  await stateStore.createProject(channelKey);
  await stateStore.updateProject(channelKey, (current) => ({
    ...current,
    workspacePath,
    repoPath,
    projectName: "demo-app",
    projectTitle: "Demo App",
    changeName,
    changeDir,
    status: "planning",
    phase: "planning_sync",
    planningJournal: {
      dirty: true,
      entryCount: 1,
      lastEntryAt: new Date(Date.now() - 60_000).toISOString(),
      lastSyncedAt: new Date(Date.now() - 120_000).toISOString(),
    },
    execution: {
      mode: "apply",
      action: "plan",
      state: "armed",
      armedAt: new Date().toISOString(),
    },
  }));

  const repoStatePaths = getRepoStatePaths(repoPath, "archives");
  const journalStore = new PlanningJournalStore(repoStatePaths.planningJournalFile);
  await journalStore.append({
    timestamp: new Date(Date.now() - 60_000).toISOString(),
    changeName,
    role: "user",
    text: "refresh the change to reflect the two new interfaces",
  });

  await manager.start();
  await manager.wake(channelKey);
  await waitFor(async () => (await stateStore.getActiveProject(channelKey))?.status === "ready");
  await manager.stop();

  const project = await stateStore.getActiveProject(channelKey);
  assert.deepEqual(runOrder, ["proposal", "specs", "design", "tasks"]);
  assert.equal(project?.status, "ready");
  assert.equal(project?.planningJournal?.dirty, false);
  assert.equal(await journalStore.hasUnsyncedChanges(changeName, repoStatePaths.planningJournalSnapshotFile), false);
  assert.equal(notifierMessages.some((message) => message.includes("Planning ready. Next: run `cs-work`")), true);
});

test("watcher restarts planning worker after ACP runtime exit", async () => {
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), "clawspec-watcher-plan-restart-"));
  const workspacePath = path.join(tempRoot, "workspace");
  const repoPath = path.join(workspacePath, "demo-app");
  const changeName = "watch-plan-restart";
  const changeDir = path.join(repoPath, "openspec", "changes", changeName);
  const proposalPath = path.join(changeDir, "proposal.md");
  await mkdir(changeDir, { recursive: true });
  await writeUtf8(path.join(changeDir, ".openspec.yaml"), "schema: spec-driven\n");

  const stateStore = new ProjectStateStore(tempRoot, "archives");
  await stateStore.initialize();
  const notifierMessages: string[] = [];
  let runCount = 0;

  const fakeAcpClient = {
    agentId: "codex",
    runTurn: async () => {
      runCount += 1;
      if (runCount === 1) {
        throw new Error("acpx exited with code 1");
      }
      await writeUtf8(proposalPath, "# Proposal\n\nRecovered after restart.\n");
      await writeJsonFile(getRepoStatePaths(repoPath, "archives").executionResultFile, {
        version: 1,
        changeName,
        mode: "apply",
        status: "running",
        timestamp: new Date().toISOString(),
        summary: "Updated proposal.",
        progressMade: true,
        currentArtifact: "proposal",
        changedFiles: ["openspec/changes/watch-plan-restart/proposal.md"],
        notes: ["Proposal refreshed"],
        taskCounts: { total: 1, complete: 0, remaining: 1 },
      });
    },
    cancelSession: async () => undefined,
    closeSession: async () => undefined,
  };

  const manager = new WatcherManager({
    stateStore,
    openSpec: createPlanningOpenSpec(changeDir, proposalPath),
    archiveDirName: "archives",
    logger: createLogger(),
    notifier: { send: async (_: string, text: string) => { notifierMessages.push(text); } } as any,
    acpClient: fakeAcpClient as any,
    pollIntervalMs: 25,
  });

  const channelKey = "discord:watch-plan-restart:default:main";
  await stateStore.createProject(channelKey);
  await stateStore.updateProject(channelKey, (current) => ({
    ...current,
    workspacePath,
    repoPath,
    projectName: "demo-app",
    projectTitle: "Demo App",
    changeName,
    changeDir,
    status: "planning",
    phase: "planning_sync",
    planningJournal: {
      dirty: true,
      entryCount: 1,
      lastEntryAt: new Date(Date.now() - 60_000).toISOString(),
    },
    execution: {
      mode: "apply",
      action: "plan",
      state: "armed",
      armedAt: new Date().toISOString(),
    },
  }));

  await manager.start();
  await manager.wake(channelKey);
  await waitFor(async () => (await stateStore.getActiveProject(channelKey))?.status === "ready", 8_000);
  await manager.stop();

  const project = await stateStore.getActiveProject(channelKey);
  assert.equal(project?.status, "ready");
  assert.equal(runCount, 2);
  assert.equal(notifierMessages.some((message) => message.includes("Restarting ACP worker")), true);
  assert.equal(notifierMessages.some((message) => message.includes("Planning ready. Next: run `cs-work`")), true);
});
