import type { RepoStatePaths } from "../utils/paths.ts";
import { tryReadUtf8, writeUtf8 } from "../utils/fs.ts";

const WORKER_IO_HELPER_SOURCE = [
  'import fs from "node:fs";',
  'import path from "node:path";',
  'import { fileURLToPath } from "node:url";',
  "",
  'const ROOT = path.dirname(fileURLToPath(import.meta.url));',
  'const PROGRESS_FILE = path.join(ROOT, "worker-progress.jsonl");',
  'const RESULT_FILE = path.join(ROOT, "execution-result.json");',
  "",
  "function nowIso() {",
  "  return new Date().toISOString();",
  "}",
  "",
  "function usage(message) {",
  "  if (message) {",
  "    console.error(message);",
  "  }",
  '  console.error("usage:");',
  '  console.error("  worker_io.mjs event --kind <kind> --current <n> --total <n> --task-id <id> --message <text>");',
  '  console.error("  worker_io.mjs result --file <json-file>");',
  "  process.exit(1);",
  "}",
  "",
  "function parseFlags(argv) {",
  "  const flags = {};",
  "  for (let index = 0; index < argv.length; index += 1) {",
  "    const token = argv[index];",
  '    if (!token || !token.startsWith("--")) {',
  '      usage(`unexpected argument: ${token ?? "<missing>"}`);',
  "    }",
  "    const key = token.slice(2);",
  "    const value = argv[index + 1];",
  "    if (!key) {",
  '      usage("flag name cannot be empty");',
  "    }",
  "    if (value === undefined) {",
  '      usage(`missing value for --${key}`);',
  "    }",
  "    flags[key] = value;",
  "    index += 1;",
  "  }",
  "  return flags;",
  "}",
  "",
  "function requireFlag(flags, key) {",
  "  const value = flags[key];",
  '  if (typeof value !== "string" || value.trim() === "") {',
  '    usage(`missing --${key}`);',
  "  }",
  "  return value;",
  "}",
  "",
  "function requireInteger(flags, key) {",
  "  const raw = requireFlag(flags, key);",
  "  const parsed = Number.parseInt(raw, 10);",
  "  if (!Number.isFinite(parsed) || parsed < 0) {",
  '    usage(`invalid integer for --${key}: ${raw}`);',
  "  }",
  "  return parsed;",
  "}",
  "",
  "function appendEvent(flags) {",
  "  const payload = {",
  "    version: 1,",
  "    timestamp: nowIso(),",
  '    kind: requireFlag(flags, "kind"),',
  '    current: requireInteger(flags, "current"),',
  '    total: requireInteger(flags, "total"),',
  '    taskId: requireFlag(flags, "task-id"),',
  '    message: requireFlag(flags, "message"),',
  "  };",
  "  fs.mkdirSync(path.dirname(PROGRESS_FILE), { recursive: true });",
  '  fs.appendFileSync(PROGRESS_FILE, JSON.stringify(payload) + "\\n", "utf8");',
  "}",
  "",
  "function writeResult(flags) {",
  '  const inputFile = requireFlag(flags, "file");',
  '  const payload = JSON.parse(fs.readFileSync(inputFile, "utf8"));',
  '  if (!payload || typeof payload !== "object" || Array.isArray(payload)) {',
  '    usage("result payload must be a JSON object");',
  "  }",
  "  if (!payload.version) {",
  "    payload.version = 1;",
  "  }",
  "  if (!payload.timestamp) {",
  "    payload.timestamp = nowIso();",
  "  }",
  "  fs.mkdirSync(path.dirname(RESULT_FILE), { recursive: true });",
  '  fs.writeFileSync(RESULT_FILE, `${JSON.stringify(payload, null, 2)}\\n`, "utf8");',
  "}",
  "",
  "function main(argv) {",
  "  const command = argv[2];",
  '  if (command === "event") {',
  "    appendEvent(parseFlags(argv.slice(3)));",
  "    return;",
  "  }",
  '  if (command === "result") {',
  "    writeResult(parseFlags(argv.slice(3)));",
  "    return;",
  "  }",
  '  usage(command ? `unknown command: ${command}` : "missing command");',
  "}",
  "",
  "main(process.argv);",
  "",
].join("\n");

export async function ensureWorkerIoHelper(repoStatePaths: RepoStatePaths): Promise<void> {
  const existing = await tryReadUtf8(repoStatePaths.workerIoFile);
  if (existing === WORKER_IO_HELPER_SOURCE) {
    return;
  }
  await writeUtf8(repoStatePaths.workerIoFile, WORKER_IO_HELPER_SOURCE);
}

export function buildWorkerIoEventCommandPrefix(repoStatePaths: RepoStatePaths): string {
  return `node ${quoteForShell(repoStatePaths.workerIoFile)} event`;
}

function quoteForShell(value: string): string {
  return `"${value.replace(/"/g, '\\"')}"`;
}
